/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.rubenparedes.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rubenparedes.controlador.ControladorUsuario;
import org.rubenparedes.db.Conexion;
import org.rubenparedes.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author r
 */
public class panelUsuarios extends javax.swing.JPanel {

    Conexion conexion = new Conexion();
    private final ControladorUsuario controlador = ControladorUsuario.getInstancia();
    
    /**
     * Creates new form panelUsuarios
     */
    public panelUsuarios() {
        initComponents();
        mostrarUsuarioTabla();
    }
    
    public void mostrarUsuarioTabla(){
        controlador.enlistarUsuarios();
        
        String[] encabezados = {"Id usuario", "Usuario", "Contraseña", "Id cliente", "Estado activo", "Rol"};
        int cantidadDeRegistro =  controlador.cantidadDeUsuarios();
        DefaultTableModel cabecera = new DefaultTableModel (encabezados,cantidadDeRegistro);
            
        tbl_usuarios.setModel(cabecera);
        TableModel tablaDeUsuario = tbl_usuarios.getModel ();
            for(int i =0; i < cantidadDeRegistro; i++){
                Usuario usuario =  controlador.listaDeUsuarios().get(i);
                tablaDeUsuario.setValueAt(usuario.getId_usuario(),i,0);
                tablaDeUsuario.setValueAt(usuario.getUsuario(), i, 1);
                tablaDeUsuario.setValueAt(usuario.getContraseña(), i, 2);
                tablaDeUsuario.setValueAt(usuario.getId_cliente(), i, 3);  
                tablaDeUsuario.setValueAt(usuario.isEstado_activo(), i, 4);
                tablaDeUsuario.setValueAt(usuario.isRol(), i, 5);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtRol = new javax.swing.JTextField();
        btnAgregarUsuario = new javax.swing.JButton();
        btnActualizarUsuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdUsuarioBuscar = new javax.swing.JTextField();
        btnBuscarUsuario = new javax.swing.JButton();

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id usuario", "Usuario", "Contraseña", "Id cliente", "Estado activo", "Rol"
            }
        ));
        jScrollPane1.setViewportView(tbl_usuarios);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setText("Id cliente");

        jLabel4.setText("Estado activo");

        jLabel5.setText("Rol");

        btnAgregarUsuario.setText("Agregar");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });

        btnActualizarUsuario.setText("Actualizar");
        btnActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setText("Id usuario");

        btnBuscarUsuario.setText("Buscar");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 38, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAgregarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnBuscarUsuario)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarUsuario)
                    .addComponent(btnActualizarUsuario)
                    .addComponent(jLabel6)
                    .addComponent(txtIdUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUsuario))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        usuario.setUsuario(txtUsuario.getText());
        usuario.setContraseña(txtContraseña.getText());
        usuario.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
        usuario.setEstado_activo(true);
        usuario.setRol(Boolean.parseBoolean(txtRol.getText()));
        controlador.agregarUsuario(usuario);
        
        txtUsuario.setText(" ");
        txtContraseña.setText(" ");
        txtIdCliente.setText(" ");
        txtRol.setText(" ");
        tbl_usuarios.setModel(new DefaultTableModel());
        mostrarUsuarioTabla();
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();        
        usuario.setId_usuario(Integer.parseInt(txtIdUsuarioBuscar.getText()));
        usuario = controlador.buscarUsuario(usuario);
        if(usuario == null)
            JOptionPane.showMessageDialog(null, "El dato con el id buscado, no se encuentra en la base de datos.");
        else{
            txtIdUsuarioBuscar.setText(String.valueOf(usuario.getId_usuario()));
            txtUsuario.setText(String.valueOf(usuario.getUsuario()));
            txtContraseña.setText(String.valueOf(usuario.getContraseña()));
            txtIdCliente.setText(String.valueOf(usuario.getId_cliente()));
            txtEstado.setText(String.valueOf(usuario.isEstado_activo()));
            txtRol.setText(String.valueOf(usuario.isRol()));
        }
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        usuario.setId_usuario(Integer.parseInt(txtIdUsuarioBuscar.getText()));
        usuario.setUsuario(txtUsuario.getText());
        usuario.setContraseña(txtContraseña.getText());
        usuario.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
        usuario.setEstado_activo(Boolean.parseBoolean(txtEstado.getText()));
        usuario.setRol(Boolean.parseBoolean(txtRol.getText()));
        
        controlador.actualizarUsuario(usuario);
        JOptionPane.showMessageDialog(null,"Ha actualizado los datos en la base");
        tbl_usuarios.setModel(new DefaultTableModel());
        mostrarUsuarioTabla();
        
        txtIdUsuarioBuscar.setText(" ");
        txtUsuario.setText(" ");
        txtContraseña.setText(" ");
        txtIdCliente.setText(" ");
        txtEstado.setText(" ");
        txtRol.setText(" ");
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarUsuario;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_usuarios;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdUsuarioBuscar;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
