/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.rubenparedes.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rubenparedes.controlador.ControladorCompra;
import org.rubenparedes.db.Conexion;
import org.rubenparedes.modelo.Compra;
import javax.swing.JOptionPane;

/**
 *
 * @author r
 */
public class panelCompras extends javax.swing.JPanel {

    Conexion conexion = new Conexion();
    private final ControladorCompra controlador = ControladorCompra.getInstancia();
    
    /**
     * Creates new form panelCompras
     */
    public panelCompras() {
        initComponents();
        mostrarCompraTabla();
    }
    
    public void mostrarCompraTabla(){
        controlador.enlistarCompras();
        
        String[] encabezados = {"Id compra", "Fecha Compra", "Id cliente"};
        int cantidadDeRegistro =  controlador.cantidadDeCompras();
        DefaultTableModel cabecera = new DefaultTableModel (encabezados,cantidadDeRegistro);
            
        tbl_compras.setModel(cabecera);
        TableModel tablaDeCompras = tbl_compras.getModel ();
            for(int i =0; i < cantidadDeRegistro; i++){
                Compra compra =  controlador.listaDeCompras().get(i);
                tablaDeCompras.setValueAt(compra.getId_compra(),i,0);
                tablaDeCompras.setValueAt(compra.getFecha_de_compra(), i, 1);
                tablaDeCompras.setValueAt(compra.getId_cliente(), i, 2);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_compras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaCompra = new javax.swing.JTextField();
        txtIdClienteCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdCompraBuscar = new javax.swing.JTextField();
        btnAgregarCompra = new javax.swing.JButton();
        btnActualizarCompra = new javax.swing.JButton();
        btnBuscarCompra = new javax.swing.JButton();

        tbl_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id compra", "Fecha de compra", "Id cliente"
            }
        ));
        jScrollPane1.setViewportView(tbl_compras);

        jLabel1.setText("Fecha de compra");

        jLabel2.setText("Id cliente");

        jLabel3.setText("Id compra");

        btnAgregarCompra.setText("Agregar");
        btnAgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCompraActionPerformed(evt);
            }
        });

        btnActualizarCompra.setText("Actualizar");
        btnActualizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCompraActionPerformed(evt);
            }
        });

        btnBuscarCompra.setText("Buscar");
        btnBuscarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdClienteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarCompra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdCompraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizarCompra)))
                        .addGap(26, 26, 26)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdClienteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdCompraBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarCompra)
                    .addComponent(btnBuscarCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCompraActionPerformed
        // TODO add your handling code here:
        Compra compra = new Compra();
        compra.setFecha_de_compra(txtFechaCompra.getText());
        compra.setId_cliente(Integer.parseInt(txtIdClienteCompra.getText()));
        controlador.agregarCompra(compra);
        
        txtFechaCompra.setText(" ");
        txtIdClienteCompra.setText(" ");
        tbl_compras.setModel(new DefaultTableModel());
        mostrarCompraTabla();
    }//GEN-LAST:event_btnAgregarCompraActionPerformed

    private void btnBuscarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompraActionPerformed
        // TODO add your handling code here:
        Compra compra = new Compra();        
        compra.setId_compra(Integer.parseInt(txtIdCompraBuscar.getText()));
        compra = controlador.buscarCompra(compra);
        if(compra == null)
            JOptionPane.showMessageDialog(null, "El dato con el id buscado, no se encuentra en la base de datos.");
        else{
            txtIdCompraBuscar.setText(String.valueOf(compra.getId_compra()));
            txtFechaCompra.setText(String.valueOf(compra.getFecha_de_compra()));
            txtIdClienteCompra.setText(String.valueOf(compra.getId_cliente()));
        }
    }//GEN-LAST:event_btnBuscarCompraActionPerformed

    private void btnActualizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCompraActionPerformed
        // TODO add your handling code here:
        Compra compra = new Compra();
        compra.setId_compra(Integer.parseInt(txtIdCompraBuscar.getText()));
        compra.setFecha_de_compra(txtFechaCompra.getText());
        compra.setId_cliente(Integer.parseInt(txtIdClienteCompra.getText()));
        
        controlador.actualizarCompra(compra);
        JOptionPane.showMessageDialog(null,"Ha actualizado los datos en la base");
        tbl_compras.setModel(new DefaultTableModel());
        mostrarCompraTabla();
        
        txtIdCompraBuscar.setText(" ");
        txtFechaCompra.setText(" ");
        txtIdClienteCompra.setText(" ");
    }//GEN-LAST:event_btnActualizarCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCompra;
    private javax.swing.JButton btnAgregarCompra;
    private javax.swing.JButton btnBuscarCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_compras;
    private javax.swing.JTextField txtFechaCompra;
    private javax.swing.JTextField txtIdClienteCompra;
    private javax.swing.JTextField txtIdCompraBuscar;
    // End of variables declaration//GEN-END:variables
}
