/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.rubenparedes.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rubenparedes.controlador.ControladorDetalle_compra;
import org.rubenparedes.db.Conexion;
import org.rubenparedes.modelo.detalle_compra;
import javax.swing.JOptionPane;


/**
 *
 * @author r
 */
public class panelDetalleCompra extends javax.swing.JPanel {

    Conexion conexion = new Conexion();
    private final ControladorDetalle_compra controlador = ControladorDetalle_compra.getInstancia();
    
    /**
     * Creates new form panelDetalleCompra
     */
    public panelDetalleCompra() {
        initComponents();
        mostrarDetalleCompraTabla();
    }
    
    public void mostrarDetalleCompraTabla(){
        controlador.enlistarDetalles_compra();
        
        String[] encabezados = {"Id detalle", "Id compra", "Id carro", "Cantidad"};
        int cantidadDeRegistro =  controlador.cantidadDetalleCompras();
        DefaultTableModel cabecera = new DefaultTableModel (encabezados,cantidadDeRegistro);
            
        tbl_detalles_compra.setModel(cabecera);
        TableModel tablaDetalleCompras = tbl_detalles_compra.getModel ();
            for(int i =0; i < cantidadDeRegistro; i++){
                detalle_compra detalles_compra =  controlador.listaDetalleCompras().get(i);
                tablaDetalleCompras.setValueAt(detalles_compra.getId_detalle_compra(),i,0);
                tablaDetalleCompras.setValueAt(detalles_compra.getId_compra(), i, 1);
                tablaDetalleCompras.setValueAt(detalles_compra.getId_carro(), i, 2);
                tablaDetalleCompras.setValueAt(detalles_compra.getCantidad(), i, 3);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detalles_compra = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarDetalleCompra = new javax.swing.JButton();
        txtIdCompraDetalle = new javax.swing.JTextField();
        txtIdCarroDetalle = new javax.swing.JTextField();
        txtCantidadDetalle = new javax.swing.JTextField();

        jLabel1.setText("Id compra");

        tbl_detalles_compra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id detalle compra", "Id compra", "Id carro", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tbl_detalles_compra);

        jLabel2.setText("Id carro");

        jLabel3.setText("Cantidad");

        btnAgregarDetalleCompra.setText("Agregar");
        btnAgregarDetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDetalleCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdCompraDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdCarroDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidadDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAgregarDetalleCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtIdCompraDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCarroDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarDetalleCompra)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDetalleCompraActionPerformed
        // TODO add your handling code here:
        detalle_compra detalles_compra = new detalle_compra();
        detalles_compra.setId_compra(Integer.parseInt(txtIdCompraDetalle.getText()));
        detalles_compra.setId_carro(Integer.parseInt(txtIdCarroDetalle.getText()));
        detalles_compra.setCantidad(Integer.parseInt(txtCantidadDetalle.getText()));
        controlador.agregarDetalle_compra(detalles_compra);
        
        txtIdCompraDetalle.setText(" ");
        txtIdCarroDetalle.setText(" ");
        txtCantidadDetalle.setText(" ");
        tbl_detalles_compra.setModel(new DefaultTableModel());
        mostrarDetalleCompraTabla();
    }//GEN-LAST:event_btnAgregarDetalleCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDetalleCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_detalles_compra;
    private javax.swing.JTextField txtCantidadDetalle;
    private javax.swing.JTextField txtIdCarroDetalle;
    private javax.swing.JTextField txtIdCompraDetalle;
    // End of variables declaration//GEN-END:variables
}
