/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.rubenparedes.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rubenparedes.controlador.ControladorCarro;
import org.rubenparedes.db.Conexion;
import org.rubenparedes.modelo.Carro;
import javax.swing.JOptionPane;

/**
 *
 * @author r
 */
public class panelCarros extends javax.swing.JPanel {

    Conexion conexion = new Conexion();
    private final ControladorCarro controlador = ControladorCarro.getInstancia();
    
    /**
     * Creates new form panelCarros
     */
    public panelCarros() {
        initComponents();
        mostrarCarroTabla();
    }
    
    public void mostrarCarroTabla(){
        controlador.enlistarCarros();
        
        String[] encabezados = {"Id carro", "Carro", "Modelo", "Precio"};
        int cantidadDeRegistro =  controlador.cantidadDeCarros();
        DefaultTableModel cabecera = new DefaultTableModel (encabezados,cantidadDeRegistro);
            
        tbl_carros.setModel(cabecera);
        TableModel tablaDeCarros = tbl_carros.getModel ();
            for(int i =0; i < cantidadDeRegistro; i++){
                Carro carro =  controlador.listaDeCarros().get(i);
                tablaDeCarros.setValueAt(carro.getId_carro(),i,0);
                tablaDeCarros.setValueAt(carro.getCarro(), i, 1);
                tablaDeCarros.setValueAt(carro.getModelo(), i, 2);
                tablaDeCarros.setValueAt(carro.getPrecio(), i, 3);  
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCarro = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIdCarroBuscar = new javax.swing.JTextField();
        btnBuscarCarro = new javax.swing.JButton();
        btnAgregarCarro = new javax.swing.JButton();
        btnActualizarCarro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_carros = new javax.swing.JTable();

        jLabel1.setText("Carro");

        jLabel2.setText("Modelo");

        jLabel3.setText("Precio");

        jLabel5.setText("Id carro");

        btnBuscarCarro.setText("Buscar");
        btnBuscarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCarroActionPerformed(evt);
            }
        });

        btnAgregarCarro.setText("Agregar");
        btnAgregarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarroActionPerformed(evt);
            }
        });

        btnActualizarCarro.setText("Actualizar");
        btnActualizarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCarroActionPerformed(evt);
            }
        });

        tbl_carros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id carro", "Carro", "Modelo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tbl_carros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnAgregarCarro)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarCarro)
                .addGap(137, 137, 137)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txtIdCarroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarCarro)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCarro)
                    .addComponent(btnActualizarCarro)
                    .addComponent(jLabel5)
                    .addComponent(txtIdCarroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCarro))
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarroActionPerformed
        // TODO add your handling code here:
        Carro carro = new Carro();
        carro.setCarro(txtCarro.getText());
        carro.setModelo(txtModelo.getText());
        carro.setPrecio(Float.parseFloat(txtPrecio.getText()));
        controlador.agregarCarro(carro);
        
        txtCarro.setText(" ");
        txtModelo.setText(" ");
        txtPrecio.setText(" ");
        tbl_carros.setModel(new DefaultTableModel());
        mostrarCarroTabla();
    }//GEN-LAST:event_btnAgregarCarroActionPerformed

    private void btnBuscarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCarroActionPerformed
        // TODO add your handling code here:
        Carro carro = new Carro();        
        carro.setId_carro(Integer.parseInt(txtIdCarroBuscar.getText()));
        carro = controlador.buscarCarro(carro);
        if(carro == null)
            JOptionPane.showMessageDialog(null, "El dato con el id buscado, no se encuentra en la base de datos.");
        else{
            txtIdCarroBuscar.setText(String.valueOf(carro.getId_carro()));
            txtCarro.setText(String.valueOf(carro.getCarro()));
            txtModelo.setText(String.valueOf(carro.getModelo()));
            txtPrecio.setText(String.valueOf(carro.getPrecio()));
        }
    }//GEN-LAST:event_btnBuscarCarroActionPerformed

    private void btnActualizarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCarroActionPerformed
        // TODO add your handling code here:
        Carro carro = new Carro();
        carro.setId_carro(Integer.parseInt(txtIdCarroBuscar.getText()));
        carro.setCarro(txtCarro.getText());
        carro.setModelo(txtModelo.getText());
        carro.setPrecio(Float.parseFloat(txtPrecio.getText()));
        
        controlador.actualizarCarro(carro);
        JOptionPane.showMessageDialog(null,"Ha actualizado los datos en la base");
        tbl_carros.setModel(new DefaultTableModel());
        mostrarCarroTabla();
        
        txtIdCarroBuscar.setText(" ");
        txtCarro.setText(" ");
        txtModelo.setText(" ");
        txtPrecio.setText(" ");
    }//GEN-LAST:event_btnActualizarCarroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCarro;
    private javax.swing.JButton btnAgregarCarro;
    private javax.swing.JButton btnBuscarCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_carros;
    private javax.swing.JTextField txtCarro;
    private javax.swing.JTextField txtIdCarroBuscar;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
