/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.rubenparedes.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.rubenparedes.controlador.ControladorDetalle_proveedor_carro;
import org.rubenparedes.db.Conexion;
import org.rubenparedes.modelo.detalle_proveedor_carro;
import javax.swing.JOptionPane;

/**
 *
 * @author r
 */
public class panelDetalleProveedorCarro extends javax.swing.JPanel {

    Conexion conexion = new Conexion();
    private final ControladorDetalle_proveedor_carro controlador = ControladorDetalle_proveedor_carro.getInstancia();
    
    /**
     * Creates new form panelDetalleProveedorCarro
     */
    public panelDetalleProveedorCarro() {
        initComponents();
        mostrarDetalleProveedorCarroTabla();
    }
    
    public void mostrarDetalleProveedorCarroTabla(){
        controlador.enlistarDetalle_proveedor_carro();
        
        String[] encabezados = {"Id detalle", "Id proveedor", "Id carro"};
        int cantidadDeRegistro =  controlador.cantidadDetalleProveedorCarro();
        DefaultTableModel cabecera = new DefaultTableModel (encabezados,cantidadDeRegistro);
            
        tbl_detalles_proveedor.setModel(cabecera);
        TableModel tablaDetalleProveedorCarro = tbl_detalles_proveedor.getModel ();
            for(int i =0; i < cantidadDeRegistro; i++){
                detalle_proveedor_carro detalles_proveedor_carro =  controlador.listaDetalleProveedorCarro().get(i);
                tablaDetalleProveedorCarro.setValueAt(detalles_proveedor_carro.getId_detalle_proveedor_carro(),i,0);
                tablaDetalleProveedorCarro.setValueAt(detalles_proveedor_carro.getId_proveedor(), i, 1);
                tablaDetalleProveedorCarro.setValueAt(detalles_proveedor_carro.getId_carro(), i, 2);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_detalles_proveedor = new javax.swing.JTable();
        txtIdProveedorDetalle = new javax.swing.JTextField();
        txtIdCarroDetalle = new javax.swing.JTextField();
        btnAgregarDetalleProveedorCarro = new javax.swing.JButton();

        jLabel1.setText("Id proveedor");

        jLabel2.setText("Id carro");

        tbl_detalles_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id detalle", "Id proveedor", "Id carro"
            }
        ));
        jScrollPane1.setViewportView(tbl_detalles_proveedor);

        btnAgregarDetalleProveedorCarro.setText("Agregar");
        btnAgregarDetalleProveedorCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDetalleProveedorCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdProveedorDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtIdCarroDetalle))
                .addGap(142, 142, 142)
                .addComponent(btnAgregarDetalleProveedorCarro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdProveedorDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnAgregarDetalleProveedorCarro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtIdCarroDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarDetalleProveedorCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDetalleProveedorCarroActionPerformed
        // TODO add your handling code here:
        detalle_proveedor_carro detalles_proveedor_carro = new detalle_proveedor_carro();
        detalles_proveedor_carro.setId_proveedor(Integer.parseInt(txtIdProveedorDetalle.getText()));
        detalles_proveedor_carro.setId_carro(Integer.parseInt(txtIdCarroDetalle.getText()));
        
        controlador.agregarDetalle_proveedor_carro(detalles_proveedor_carro);
        
        txtIdProveedorDetalle.setText(" ");
        txtIdCarroDetalle.setText(" ");
        tbl_detalles_proveedor.setModel(new DefaultTableModel());
        mostrarDetalleProveedorCarroTabla();
    }//GEN-LAST:event_btnAgregarDetalleProveedorCarroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDetalleProveedorCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_detalles_proveedor;
    private javax.swing.JTextField txtIdCarroDetalle;
    private javax.swing.JTextField txtIdProveedorDetalle;
    // End of variables declaration//GEN-END:variables
}
