/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.rubenparedes.vista;

/**
 *
 * @author r
 */
public class VistaVentaCarros extends javax.swing.JFrame {

    /**
     * Creates new form VistaVentaCarros
     */
    public VistaVentaCarros() {
        initComponents();
        setLocationRelativeTo(null);
        
        panelCarros pc = new panelCarros();
        pc.setSize(670,350);
        pc.setLocation(0,0);
        
        content.removeAll();
        content.add(pc);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCarrosPrincipal = new javax.swing.JButton();
        btnClientesPrincipal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnUsuariosPrincipal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnComprasPrincipal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnDetalleCompraPrincipal = new javax.swing.JButton();
        btnDetalleProveedorCarroPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(34, 68, 116));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rubenparedes/recursos/cofino.jpg"))); // NOI18N

        btnCarrosPrincipal.setText("Carros");
        btnCarrosPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrosPrincipalActionPerformed(evt);
            }
        });

        btnClientesPrincipal.setText("Clientes");
        btnClientesPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesPrincipalActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rubenparedes/recursos/cliente.png"))); // NOI18N

        btnUsuariosPrincipal.setText("Usuarios");
        btnUsuariosPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosPrincipalActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rubenparedes/recursos/usuario.png"))); // NOI18N

        btnComprasPrincipal.setText("Compras");
        btnComprasPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasPrincipalActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rubenparedes/recursos/carrito.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rubenparedes/recursos/carro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarrosPrincipal)
                    .addComponent(btnClientesPrincipal)
                    .addComponent(btnUsuariosPrincipal)
                    .addComponent(btnComprasPrincipal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCarrosPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientesPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuariosPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnComprasPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rubenparedes/recursos/toyota2.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rubenparedes/recursos/ford.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/rubenparedes/recursos/mazda.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 670, 120));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 670, 350));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        btnDetalleCompraPrincipal.setText("Detalle compra");
        btnDetalleCompraPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleCompraPrincipalActionPerformed(evt);
            }
        });

        btnDetalleProveedorCarroPrincipal.setText("Detalle proveedor carro");
        btnDetalleProveedorCarroPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleProveedorCarroPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnDetalleCompraPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btnDetalleProveedorCarroPrincipal)
                .addGap(134, 134, 134))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalleProveedorCarroPrincipal)
                    .addComponent(btnDetalleCompraPrincipal))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 670, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarrosPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrosPrincipalActionPerformed
        // TODO add your handling code here:
        panelCarros pc = new panelCarros();
        pc.setSize(670,350);
        pc.setLocation(0,0);
        
        content.removeAll();
        content.add(pc);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnCarrosPrincipalActionPerformed

    private void btnClientesPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesPrincipalActionPerformed
        // TODO add your handling code here:
        panelClientes pc2 = new panelClientes();
        pc2.setSize(670,350);
        pc2.setLocation(0,0);
        
        content.removeAll();
        content.add(pc2);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnClientesPrincipalActionPerformed

    private void btnUsuariosPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosPrincipalActionPerformed
        // TODO add your handling code here:
        panelUsuarios pu = new panelUsuarios();
        pu.setSize(670,350);
        pu.setLocation(0,0);
        
        content.removeAll();
        content.add(pu);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnUsuariosPrincipalActionPerformed

    private void btnComprasPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasPrincipalActionPerformed
        // TODO add your handling code here:
        panelCompras pc3 = new panelCompras();
        pc3.setSize(670,350);
        pc3.setLocation(0,0);
        
        content.removeAll();
        content.add(pc3);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnComprasPrincipalActionPerformed

    private void btnDetalleCompraPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleCompraPrincipalActionPerformed
        // TODO add your handling code here:
        panelDetalleCompra dc = new panelDetalleCompra();
        dc.setSize(670,350);
        dc.setLocation(0,0);
        
        content.removeAll();
        content.add(dc);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnDetalleCompraPrincipalActionPerformed

    private void btnDetalleProveedorCarroPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleProveedorCarroPrincipalActionPerformed
        // TODO add your handling code here:
        panelDetalleProveedorCarro dpc = new panelDetalleProveedorCarro();
        dpc.setSize(670,350);
        dpc.setLocation(0,0);
        
        content.removeAll();
        content.add(dpc);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnDetalleProveedorCarroPrincipalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrosPrincipal;
    private javax.swing.JButton btnClientesPrincipal;
    private javax.swing.JButton btnComprasPrincipal;
    private javax.swing.JButton btnDetalleCompraPrincipal;
    private javax.swing.JButton btnDetalleProveedorCarroPrincipal;
    private javax.swing.JButton btnUsuariosPrincipal;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
